const names = [
    'Iron Man',
    'Hulk',
    'Captain America',
    'Thor',
    'Hawkeye',
    'Black Widow',
    'Falcon',
    'Scarlet Witch',
    'Vision',
    'Spider-Man',
    'Black Panther',
    'Doctor Strange',
    'War Machine',
    'Winter Soldier',
    'Ant-Man',
    'The Wasp',
    'Star-Lord',
    'Gamora',
    'Rocket Raccoon',
    'Groot',
    'Drax the Destroyer',
    'Nebula',
    'Heimdall',
    'Mantis',
    'Wong',
    'Okoye',
    'Shuri',
    'M’Baku',
    'Thanos',
    'Loki',
    'The Collector',
    'Black Order',
    'Hela',
    'Odin',
    'Wolverine',
    'Professor X',
    'Phoenix',
    'Cyclops',
    'Storm',
    'Rogue',
    'Iceman',
    'Colossus',
    'Angel',
    'Jubilee',
    'Siryn',
    'Havok',
    'Banshee',
    'Darwin',
    'Magneto',
    'Mystique',
    'Sabretooth',
    'Toad',
    'Pyro',
    'Callisto',
    'Psylocke',
    'Juggernaut',
    'Nightcrawler',
    'Gambit',
    'Viper',
    'Quicksilver',
    'Apocalypse',
    'Shadowcat',
    'Deadpool'
];

module.exports = function () {
    var x = Math.floor(Math.random() * names.length);
    return names[x];
};